format:
  html:
    toc: true
    toc-depth: 4
    theme: [spacelab, notebooks/custom.scss]
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Kindly Noted
  chapters: [index.qmd, kindly.qmd, kinds.qmd, kindly_advice.qmd]
