project:
  type: book

format:
  html:
    theme: cosmo

book:
  title: "Kindly Noted"
  chapters:
    - index.qmd
    - temp.qmd
    - chapters/kindly-advice.qmd
    - chapters/kindly.qmd
    - chapters/note-to-test.qmd

